### ISSUE TITLE
fix var DEFAULTS from m (manual) to none for some packages, as "m" forced dependencies to be build

### ISSUE THREAD

**Issue by thuehn** [dtaht/ceropackages-3.10#17]
diff --git a/devel/libasio/Makefile b/devel/libasio/Makefile
index 657b998..9922753 100644
--- a/devel/libasio/Makefile
+++ b/devel/libasio/Makefile
@@ -27,7 +27,7 @@ include $(INCLUDE_DIR)/package.mk
 define Package/libasio
   SECTION:=libs
   CATEGORY:=Libraries
-  DEFAULT:=m
+  DEFAULT:=n
   TITLE:=libasio
   URL:=http://think-async.com/
   DEPENDS:=+boost
diff --git a/net/resiprocate/Makefile b/net/resiprocate/Makefile
index 303c269..a35dc66 100644
--- a/net/resiprocate/Makefile
+++ b/net/resiprocate/Makefile
@@ -30,7 +30,7 @@ define Package/resiprocate/Default
   SECTION:=net
   CATEGORY:=Network
   SUBMENU:=Telephony
-  DEFAULT:=m
+  DEFAULT:=n
   TITLE:=reSIProcate
   URL:=http://www.resiprocate.org/
   DEPENDS:=+libopenssl +libdb47 +libcares +boost +libstdcpp

**Comment by tohojo** [comment]
No objection to this; any chance you could do a pull request?

**Comment by thuehn** [comment]
sure ... sould be on request

**Comment by tohojo** [comment]
Awesome, thanks!
