### ISSUE TITLE
Remove sched_fq_pie dependency from tc-adv until it can compile so that Cake shaper can be installed

### ISSUE THREAD

**Issue by minecraft2048** [dtaht/ceropackages-3.10#20]
I want to try Cake shaper with Openwrt in my old PC, so I followed this information: https://www.bufferbloat.net/projects/codel/wiki/Cake/ to install Cake to Openwrt

```
Target Profile -> TP-LINK Archer C5/C7

Luci -> Collections -> Luci (*)
        Applications -> luci-app-sqm (*)
Kernel Modules -> Network Support -> kmod-sched-cake & kmod-sched-fq_pie (*)
Network -> Routing & Redirection -> tc-adv (*)
```
replacing the Target Profile with x86_64 generic. Then, I tried to make it, then this error happens: https://github.com/dtaht/sched_fq_pie/issues/1 . After manually removing sched_fq_pie as a hard dependency to tc-adv in the Makefiles, OpenWrt compiles normally

**Comment by majster95** [comment]
I have the same problem during compiling, but remove sched_fq_pie from tc-adv makefile doesn't help me. Can you explain me how yo did this ?

**Comment by minecraft2048** [comment]
@majster95 My bad, I think that it is not in the makefile, you should go to ./tmp/.config-package.in, search for tc-adv and remove both `depends on` and `select`, with that, you can go to the `make menuconfig` and unselect sched_fq_pie, then you can compile as usual

**Comment by majster95** [comment]
Thank you ;) 
I will test it tomorrow.

**Comment by dtaht** [comment]
May I close this?

**Comment by minecraft2048** [comment]
Yes? Its been a long time for me to play with this stuff
